import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Playfair Display', 'Georgia', 'serif'],
        'headline-md': ['Playfair Display', 'Georgia', 'serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Playfair Display', 'Georgia', 'serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      colors: {
        // Stitch FinTrack fintech palette
        'on-tertiary-container': '#8c8e8f',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#bac6ea',
        'tertiary-fixed-dim': '#c5c7c8',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#e1e3e4',
        'primary-container': '#1a2642',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        tertiary: '#101213',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-primary-fixed-variant': '#3b4664',
        'on-secondary-fixed-variant': '#5c4300',
        'surface-container': '#e5eeff',
        'outline-variant': '#c6c6ce',
        'on-tertiary-fixed-variant': '#454748',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        secondary: '#795900',
        'secondary-fixed-dim': '#f6be39',
        'surface-dim': '#cbdbf5',
        'secondary-container': '#ffc641',
        'surface-variant': '#d3e4fe',
        'on-primary-container': '#828daf',
        'primary-fixed-dim': '#bac6ea',
        'on-secondary-fixed': '#261a00',
        'surface-tint': '#525e7d',
        'on-surface-variant': '#45464d',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#715300',
        outline: '#75777e',
        'surface-container-low': '#eff4ff',
        'tertiary-container': '#242728',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ffdfa0',
        'on-tertiary-fixed': '#191c1d',
        'on-error-container': '#93000a',
        'inverse-surface': '#213145',
        'primary-fixed': '#d9e2ff',
        'on-primary-fixed': '#0e1b36',
        error: '#ba1a1a',
        // Shadcn semantic tokens (mapped to Stitch)
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Legacy aliases
        navy: {
          DEFAULT: '#1a2642',
          50: '#eff4ff',
          100: '#dce9ff',
          200: '#bac6ea',
          300: '#828daf',
          400: '#525e7d',
          500: '#3b4664',
          600: '#1a2642',
          700: '#04112c',
          800: '#0b1c30',
          900: '#04112c',
        },
        gold: {
          DEFAULT: '#ffc641',
          50: '#ffdfa0',
          100: '#ffc641',
          200: '#f6be39',
          300: '#795900',
          400: '#715300',
          500: '#ffc641',
          600: '#f6be39',
          700: '#795900',
          800: '#5c4300',
          900: '#261a00',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        'margin-mobile': '20px',
        gutter: '24px',
        'unit-xs': '4px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        'unit-lg': '32px',
        'unit-md': '16px',
        'unit-sm': '8px',
      },
      maxWidth: {
        container: '1280px',
      },
      boxShadow: {
        premium: '0 10px 30px -10px rgba(4, 17, 44, 0.15)',
        glass: '0 4px 20px rgba(4, 17, 44, 0.08)',
        gold: '0 0 10px rgba(255, 223, 160, 0.5)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        float: 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [animate],
};

export default config;
