import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { PassportService } from './passport.service';
import type { PassportPayload } from './dto/passport.dto';

/**
 * Generates a PDF export of the Digital Business Passport (PASS-05).
 */
@Injectable()
export class PassportPdfService {
  constructor(private readonly passportService: PassportService) {}

  async generateForOwner(ownerId: string): Promise<Buffer> {
    const passport = await this.passportService.getPassport(ownerId);
    return this.renderPdf(passport);
  }

  private renderPdf(data: PassportPayload): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(22).fillColor('#1A2642').text('FinTrack', { align: 'center' });
      doc.fontSize(14).fillColor('#666666').text('Digital Business Passport', { align: 'center' });
      doc.moveDown(1.5);

      doc.fontSize(11).fillColor('#1A2642');
      doc.text(`Passport ID: ${data.passportId}`, { continued: false });
      doc.text(`Generated: ${new Date(data.generatedAt).toLocaleDateString()}`);
      doc.moveDown();

      doc.fontSize(16).text('Business Profile', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333333');
      doc.text(`Name: ${data.business.name}`);
      doc.text(`Type: ${data.business.type}`);
      doc.text(`Industry: ${data.business.industry}`);
      doc.text(`Location: ${data.business.location}`);
      doc.text(`Years Operating: ${data.business.yearsOperating}`);
      doc.text(`Employees: ${data.business.numEmployees}`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#1A2642').text('Health Score', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333333');
      doc.text(`Overall Score: ${data.healthScore}/100`);
      doc.text(`Credit Readiness: ${data.creditReadiness.label} (${data.creditReadiness.level})`);
      doc.text(`Records: ${data.healthScoreBreakdown.records}%`);
      doc.text(`Consistency: ${data.healthScoreBreakdown.consistency}%`);
      doc.text(`Debt Management: ${data.healthScoreBreakdown.debtManagement}%`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#1A2642').text('Activity Summary', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333333');
      doc.text(`Transactions: ${data.activitySummary.transactionsRecorded}`);
      doc.text(`Documents: ${data.activitySummary.documentsUploaded}`);
      doc.text(`Customers: ${data.activitySummary.customersRegistered}`);
      doc.text(`Debts Resolved: ${data.activitySummary.debtsResolved}`);
      doc.moveDown();

      doc.fontSize(16).fillColor('#1A2642').text('Improvement Checklist', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333333');
      for (const item of data.improvementChecklist) {
        doc.text(`${item.completed ? '[x]' : '[ ]'} ${item.id}`);
      }

      doc.moveDown(2);
      doc
        .fontSize(9)
        .fillColor('#999999')
        .text(
          'This document was generated by FinTrack. Health scores are computed server-side and reflect business activity at time of export.',
          { align: 'center' },
        );

      doc.end();
    });
  }
}
